version: '3.7'
services:

  web:
    container_name: shop
    build:
      context: ./shop
      args:
        - RUN_DB_MIGRATIONS_ARG=yes
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shop:/code
    ports:
      - '8000:8000'
    env_file:
      - ./.env      
    depends_on:
      - db
  db:
    container_name: postgres_shop
    image: postgres:12.0
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
 
networks:
  postgres:
    driver: bridge
 
volumes:
  postgres_data: